### ISSUE TITLE
failed to start ion

### ISSUE THREAD

**Issue by johnnychen94** [Roger-luo/IonCLI.jl#24]
```
bash-3.2$ ion
ERROR: could not load library "/Users/jc/.julia/packages/IonCLI/DJ2Ch/deps/lib/libion.dylib"
dlopen(/Users/jc/.julia/packages/IonCLI/DJ2Ch/deps/lib/libion.dylib, 6): no suitable image found.  Did find:
	/Users/jc/.julia/packages/IonCLI/DJ2Ch/deps/lib/libion.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
	/Users/jc/.julia/packages/IonCLI/DJ2Ch/deps/lib/libion.dylib: stat() failed with errno=38
/Users/jc/.julia/bin/ion: line 6: 19182 Segmentation fault: 11  JULIA_PROJECT=/Users/jc/.julia/packages/IonCLI/DJ2Ch /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia -J/Users/jc/.julia/packages/IonCLI/DJ2Ch/deps/lib/libion.dylib --compile=min -O2 -- /Users/jc/.julia/bin/ion.jl $@

bash-3.2$ echo $PATH
/Users/jc/.local/bin:/Applications/Julia-1.0.app/Contents/Resources/julia/bin/:/Users/jc/bin:/Users/jc/opt/anaconda3/condabin:/Users/jc/.cargo/bin:/Users/jc/.julia/bin:/Users/jc/opt/anaconda3/bin:/Users/jc/.local/bin:/Users/jc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:.:/usr/local/opt/fzf/bin

bash-3.2$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_PKG_SERVER = https://mirrors.sjtug.sjtu.edu.cn/julia
```

OS: `macOS Catalina 10.15.6`

I also tried this in an empty `JULIA_DEPOT_PATH` with PATH modified accordingly, and it's the same error.

**Comment by johnnychen94** [comment]
fixed with a locally compiled binary:

`using IonCLI; IonCLI.comonicon_build()`

**Comment by Roger-luo** [comment]
It seems this has something to do while compiling with Manifest.toml using PackageCompiler on Mac OS.

**Comment by johnnychen94** [comment]
I believe this is now fixed as the build process falls back to build sysimage locally. CRef: https://github.com/Roger-luo/Comonicon.jl/issues/59

**Comment by Roger-luo** [comment]
I still want to keep this open, since the actual issue is not resolved (on PackageCompiler side)

**Comment by Roger-luo** [comment]
I realize this is because the wrong cpu_target. It should use the default app cpu target instead generic x86_64.
